### Q1 Write a program to create an array of shape  5X4 containing elements 1 to 20 find the sum of entire array well as well as sum of each row and column

In [1]:
import numpy as np

arr = np.arange(1,21)

arr_2D = arr.reshape(5,4)

print(arr_2D)

print("The Sum will be: ",np.sum(arr))

print("The Sum of Rows will be: ",np.sum(arr_2D,axis=0))

print("The Sum of Columns will be: ",np.sum(arr_2D,axis=1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
The Sum will be:  210
The Sum of Rows will be:  [45 50 55 60]
The Sum of Columns will be:  [10 26 42 58 74]



### Q2 Create a array of size 10 with each element of it set as value 3 and find the memory size of this array and it's indivisiul element.



In [2]:
arr2 = np.full(10,3)

print(arr2)

print(arr2.nbytes)

print(arr2.itemsize)

[3 3 3 3 3 3 3 3 3 3]
80
8


### Q3 Create an array b of size 10 with ranging 0 to 90 evenly space.



In [3]:
arr3 = np.linspace(0,90,10)

print(arr3)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


### Q4 Reverse elements of array arr3



In [4]:
print(np.flip(arr3, axis=None))

[90. 80. 70. 60. 50. 40. 30. 20. 10.  0.]


### Q5 Add arrays arr2 and arr3 and store it on result arr4 array.

In [5]:
arr4 = np.add(arr2,arr3)

print(arr4)

[ 3. 13. 23. 33. 43. 53. 63. 73. 83. 93.]
